name: laundry
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  share_extend: ^1.1.9
  screen: ^0.0.5
  flutter_local_notifications: ^1.4.4+4
  background_location:
  http:
  firebase_database:
  shared_preferences:
  fluttertoast:
  location:
  geolocator:
  cloud_firestore:
  intl: ^0.16.1
  flutter:
    sdk: flutter
  connectivity: ^0.4.8+2
  flare_flutter: ^2.0.5
  cupertino_icons: ^0.1.2
  google_maps_flutter: 0.5.26+2
  google_map_polyline:
  firebase_storage:
#  table_calendar:
  flutter_calendar_carousel:
  pdf:
#  workmanager: ^0.2.3
  path_provider:
  flutter_pdfview:
  permission_handler: ^5.0.1+1
  firebase_messaging: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/network.gif
    - images/profileimg.png
    - assets/profile1.png
    - images/loading.gif
    - images/12.jpg
    - images/laundry.png
    - images/image1.jpg
    - images/success.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/Myriad_Pro_Regular.ttf
    - family: Myriad_Bold
      fonts:
        - asset: assets/fonts/Myriad_Pro_Bold.ttf

    - family: Seguisb
      fonts:
        - asset: assets/fonts/seguisb.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: Franklin
      fonts:
        - asset: assets/fonts/Franklin Gothic Demi Regular.ttf
    - family: phagspa
      fonts:
        - asset: assets/fonts/phagspa.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
